export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
